### ISSUE TITLE
Erroneously  Low Accuracy in Tensorflow Version & RuntimeError in PyTorch Version

### ISSUE THREAD

**Issue by yoshi2233** [daiquocnguyen/QGNN#1]
Hi there,

I've noticed that the Tensorflow version of the QGNN has erroneously low accuracy (python 3.8.2, tensorflow 2.4.0).

Script:
`python train_node_cls.py --dataset cora --learning_rate 0.05 --hidden_size 16 --epochs 100 --fold 2`

PyTorch:
```
Epoch: 0100 loss_train: 0.3678 acc_train: 0.8960 loss_val: 0.4513 acc_val: 0.8606 time: 0.3034s
Optimization Finished!
Total time elapsed: 33.9790s
Test set results: loss= 0.3706 accuracy= 0.8934
```

Tensorflow:
```
Epoch: 0100 train_loss= 0.50750 train_acc= 0.90352 val_loss= nan val_acc= 0.14196 time= 0.03599
Optimization Finished!
Test set results at final epoch: cost= nan accuracy= 0.13481 time= 0.02022
```

**As you can see `cost` is a NaN and `accuracy` is 0.13481, which is far lower than that of the PyTorch version (0.8934).**

Also, I get the following error when I try to run the script below using the PyTorch version (torch 1.6.0).

Script:
`python train_node_cls.py --dataset citeseer --learning_rate 0.05 --hidden_size 16 --epochs 100 --fold 4`

PyTorch:
```
train_node_cls.py:56: RuntimeWarning: divide by zero encountered in power
  r_inv = np.power(rowsum, -1).flatten()
Traceback (most recent call last):
  File "train_node_cls.py", line 129, in <module>
    train(epoch)
  File "train_node_cls.py", line 97, in train
    output = model(features, adj)
  File "/home/satyoshi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train_node_cls.py", line 84, in forward
    x = self.q4gnn1(x, adj)
  File "/home/satyoshi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/data/programming/machinelearning/QGNN-master/QGNN_pytorch/q4gnn.py", line 77, in forward
    support = torch.mm(x, hamilton)  # Hamilton product, quaternion multiplication!
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out
```

Tensorflow:
```
Epoch: 0100 train_loss= 0.61921 train_acc= 0.85939 val_loss= nan val_acc= 0.06333 time= 0.06901
Optimization Finished!
Test set results at final epoch: cost= nan accuracy= 0.06132 time= 0.04012
```

The error does not occur with the Tensorflow version, but still it has the same NaN issue as above.

Best,
JS

**Comment by daiquocnguyen** [comment]
Hi JS,

I reported all results in our paper using Tensorflow 1.14. You can see the requirements in README. I will plan to release the implementation using Tensorflow 2.x when I have time.

Regarding the Pytorch implementation, you can see my comments in q4gnn.py that there is a difference in scalar type between node and graph classification tasks when loading the input datasets. I maintain the Pytorch code for most of the cases.

Best regards,
Dai.
